# Generated by Django 4.2.2 on 2023-07-26 17:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Barrios",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=200)),
                ("siglas", models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name="Personas",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombres", models.CharField(max_length=300)),
                ("apellidos", models.CharField(max_length=300)),
                ("cedula", models.CharField(max_length=10)),
                ("correo", models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name="Localrepuestos",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "direccion",
                    models.CharField(max_length=300, verbose_name="direccion"),
                ),
                ("valor_mecaderia", models.FloatField()),
                ("comida_tipo", models.CharField(max_length=50)),
                ("ventas_proyectadas", models.CharField(max_length=200)),
                ("permiso_pago", models.FloatField()),
                (
                    "barrio",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="locales.barrios",
                    ),
                ),
                (
                    "propietario",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="locales.personas",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Localcomida",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("direccion", models.CharField(max_length=300)),
                ("comida_tipo", models.CharField(max_length=500)),
                ("ventas_proyectadas", models.IntegerField()),
                ("permiso_pago", models.FloatField()),
                (
                    "barrio",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="locales.barrios",
                    ),
                ),
                (
                    "propietario",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="locales.personas",
                    ),
                ),
            ],
        ),
    ]
