# Generated by Django 4.2.2 on 2023-07-27 00:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("locales", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="localcomida",
            name="ventas_proyectadas",
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name="localrepuestos",
            name="ventas_proyectadas",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
