# Generated by Django 4.2.2 on 2023-07-27 01:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("locales", "0002_alter_localcomida_ventas_proyectadas_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="localrepuestos",
            name="ventas_proyectadas",
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
    ]
