# Generated by Django 4.2.2 on 2023-07-17 04:54

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Barrio",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=200)),
                ("siglas", models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name="LocalesComida",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "propietario",
                    models.CharField(
                        choices=[("", ""), ("", "")],
                        max_length=500,
                        verbose_name="propietario",
                    ),
                ),
                ("direccion", models.CharField(max_length=300)),
                (
                    "barrio",
                    models.CharField(
                        choices=[("rural", "rural"), ("úrbano", "úrbano")],
                        max_length=255,
                    ),
                ),
                ("comida_tipo", models.CharField(max_length=500)),
                ("ventas_proyectadas", models.IntegerField()),
                ("permiso", models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name="LocalesRepuestos",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "propietario",
                    models.CharField(
                        choices=[("", ""), ("", "")],
                        max_length=500,
                        verbose_name="propietario",
                    ),
                ),
                ("direccion", models.CharField(max_length=300)),
                ("valor_mecaderia", models.FloatField()),
                ("permiso", models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name="Persona",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=300)),
                ("apellido", models.CharField(max_length=300)),
                ("cedula", models.CharField(max_length=10)),
                ("correo", models.EmailField(max_length=254)),
            ],
        ),
    ]
