# Generated by Django 4.2.2 on 2023-07-17 04:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("locales_app", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="localescomida",
            name="barrio",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="locales_app.barrio"
            ),
        ),
        migrations.AlterField(
            model_name="localescomida",
            name="propietario",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="locales_app.persona"
            ),
        ),
        migrations.AlterField(
            model_name="localesrepuestos",
            name="propietario",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="locales_app.persona"
            ),
        ),
    ]
