# Generated by Django 4.2.2 on 2023-07-21 04:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("locales_app", "0002_alter_localescomida_barrio_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="localesrepuestos",
            name="barrio",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="locales_app.barrio",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="localesrepuestos",
            name="comida_tipo",
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="localesrepuestos",
            name="ventas_proyectadas",
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
    ]
